AWSTemplateFormatVersion: '2010-09-09'
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 15
Parameters:
  DBCapacity:
    Default: 20
    Type: Number
  DBName:
    Default: JackProdDB
    Type: String
  DBPassword:
    Default: ArgosBubble3
    Type: String
  DBType:
    Default: db.t2.micro
    Type: String
  DBUsername:
    Default: JackAdmin
    Type: String
Resources:
  CreateCategory:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /business/category/create
          Type: Api
      Handler: createCategory
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  CreateOrder:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /business/order/create
          Type: Api
      Handler: createOrder
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  CreateProduct:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /business/product/create
          Type: Api
      Handler: createProduct
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  CreateUser:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /user/create
          Type: Api
      Handler: createUser
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  GetBusinessStocks:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /business/stocks
          Type: Api
      Handler: getBusinessStocks
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  GetUsers:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /user
          Type: Api
      Handler: getUsers
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  JackAuthorizer:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Handler: jackAuthorizer
      Runtime: go1.x
    Type: AWS::Serverless::Function
  LogBusiness:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /business/log
          Type: Api
      Handler: logBusiness
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  LogUser:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /user/log
          Type: Api
      Handler: logUser
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  ResetDB:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /utils/reset
          Type: Api
      Handler: resetDB
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  createBusiness:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /business/create
          Type: Api
      Handler: createBusiness
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  deleteItem:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /delete
          Type: Api
      Handler: deleteItem
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  getBusinessById:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /business
          Type: Api
      Handler: getBusinessById
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  getCategories:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /category
          Type: Api
      Handler: getCategories
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  getOrders:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /order
          Type: Api
      Handler: getOrders
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  getProducts:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /product
          Type: Api
      Handler: getProducts
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  ordersWatcher:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /order/watcher
          Type: Api
      Handler: ordersWatcher
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  updateBusiness:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /business/update
          Type: Api
      Handler: updateBusiness
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  updateCategory:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /category/update
          Type: Api
      Handler: updateCategory
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  updateOrder:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /order/update
          Type: Api
      Handler: updateOrder
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  updateProduct:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /product/update
          Type: Api
      Handler: updateProduct
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  updateUser:
    Properties:
      CodeUri: s3://jack-world-app/56d4ff6b3f289c9923298e4d7bf86cae
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /user/update
          Type: Api
      Handler: updateUser
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
