AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10

# Parameters: 
#   userTableName: 
#     Type: String
#   Default: "myapp.User"
#   Description: "Name of the user table"
# userIndexName: 
#   Type: String
#   Default: "user-city-index"
#   Description: "Name of the user index"

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: main
      Runtime: go1.x
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

  # Business
  CreateBusiness:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: createBusiness
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
#        - arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /business/create
            Method: post
  GetBusinessById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: getBusinessById
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /business
            Method: get
  GetProductsById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: getProductsById
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /product
            Method: get
  GetBusinessInArea:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: getBusinessInArea
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /business/area
            Method: get
  GetBusinessOrders:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: getBusinessOrders
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /business/orders
            Method: get
  GetBusinessStocks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: getBusinessStocks
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /business/stocks
            Method: get

  # Order
  CreateOrder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: createOrder
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /business/order/create
            Method: post

  # Stock
  CreateProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: createProduct
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /business/product/create
            Method: post
  CreateCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: createCategory
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /business/category/create
            Method: post

  ResetDB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: resetDB
      Runtime: go1.x
      Timeout: 10
      Role: arn:aws:iam::318620884208:role/LambdaVPCAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /utils/reset
            Method: get
#  JackDB:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      AttributeDefinitions:
#        -
#          AttributeName: "id"
#          AttributeType: "S"
#      KeySchema:
#        -
#          AttributeName: "id"
#          KeyType: "HASH"
#      ProvisionedThroughput:
#        ReadCapacityUnits: 5
#        WriteCapacityUnits: 5
#      TableName: "JackDB"



#  BusinessTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      TableName: "BusinessTabler"
#      KeySchema:
#        -
#          AttributeName: "UUID"
#          KeyType: "HASH"
#      AttributeDefinitions:
#        -
#          AttributeName: "UUID"
#          AttributeType: "S"
#        -
#          AttributeName: "name"
#          AttributeType: "S"
#        -
#          AttributeName: "address"
#          AttributeType: "S"
##        -
##          AttributeName: "name"
##          KeyType: "RANGE"
#      GlobalSecondaryIndexes:
#        -
#          IndexName: "BusinessIndex"
#          KeySchema:
#            -
#              AttributeName: "name"
#              KeyType: "RANGE"
#            -
#              AttributeName: "address"
#              KeyType: "RANGE"
#          Projection:
#            ProjectionType: "ALL"
#          ProvisionedThroughput:
#            ReadCapacityUnits: 5
#            WriteCapacityUnits: 5
#      ProvisionedThroughput:
#        ReadCapacityUnits: 5
#        WriteCapacityUnits: 5
#  WriteCapacityScalableTarget:
#    Type: AWS::ApplicationAutoScaling::ScalableTarget
#    Properties:
#      MaxCapacity: 15
#      MinCapacity: 5
#      RoleARN: !GetAtt ScalingRole.Arn
#      ResourceId: !Join
#        - /
#        - - table
##          - !Ref JackDB
#          - !Ref BusinessTable
#      ScalableDimension: dynamodb:table:WriteCapacityUnits
#      ServiceNamespace: dynamodb
#  ScalingRole:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: "2012-10-17"
#        Statement:
#          -
#            Effect: "Allow"
#            Principal:
#              Service:
#                - application-autoscaling.amazonaws.com
#            Action:
#              - "sts:AssumeRole"
#      Path: "/"
#      Policies:
#        -
#          PolicyName: "root"
#          PolicyDocument:
#            Version: "2012-10-17"
#            Statement:
#              -
#                Effect: "Allow"
#                Action: "*"
#                Resource: "*"


#  PostgresCluster:
#      DependsOn: PostgresSecurityGroup
#      Type: AWS::RDS::DBInstance
#      Properties:
#          Engine: MySQL
#          DBName: "Jacking"
#          MasterUsername: "Arthur"
#          MasterUserPassword: ""
#          DBInstanceClass: !Ref DBType
#          AllocatedStorage: !Ref DBCapacity
#          DBSubnetGroupName: !Ref PostgresSubnetGroup
#          VPCSecurityGroups:
#              - !GetAtt PostgresSecurityGroup.GroupId

#  WriteScalingPolicy:
#    Type: AWS::ApplicationAutoScaling::ScalingPolicy
#    Properties:
#      PolicyName: WriteAutoScalingPolicy
#      PolicyType: TargetTrackingScaling
#      ScalingTargetId: !Ref WriteCapacityScalableTarget
#      TargetTrackingScalingPolicyConfiguration:
#        TargetValue: 50.0
#        ScaleInCooldown: 60
#        ScaleOutCooldown: 60
#        PredefinedMetricSpecification:
#          PredefinedMetricType: DynamoDBWriteCapacityUtilization

Outputs:

  Endpoint:
    Value:  !Sub "http://jack-world-app.s3-website.eu-west-2.amazonaws.com/Prod/"
